# Generated by Django 3.1.4 on 2021-01-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210110_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Inbox', 'verbose_name_plural': 'Messages'},
        ),
    ]
